### ISSUE TITLE
XP Bug when you level.sav to increase character level

### ISSUE THREAD

**Issue by dungtranhoang** [cheahjs/palworld-save-tools#106]
Hi I just wanna to ask, I use the v15 (latest) to convert to json
Then after that I look for character name to increase their level (from 35 to 37) But after that, the XP need for level from 37 to 38 seem like too much (appx 600k XP)
compare with my char when level 41 that need around 200k
Does anything else I need to change to make this normally?
![image](https://github.com/cheahjs/palworld-save-tools/assets/124852753/f668294a-5255-4b41-8de6-01f803035ab1)
Or it just normal?

**Comment by cheahjs** [comment]
You likely need to modify the `Exp` field as well.
