### ISSUE TITLE
Unicode in value for nickname, guild etc...

### ISSUE THREAD

**Issue by mazixs** [cheahjs/palworld-save-tools#107]
I get an output file with unicode
sample values (\u6355\u7372\u7387)
Russian is used in the names of pals, guilds, nicknames.
How its change or read? 

![Screenshot_4](https://github.com/cheahjs/palworld-save-tools/assets/13685616/014a4733-6927-46f9-8e42-02c151a722c5)
![Screenshot_3](https://github.com/cheahjs/palworld-save-tools/assets/13685616/cf6551d1-4e8e-459a-8c06-4d362818a080)

Used version 0.16

**Comment by cheahjs** [comment]
You can use something like https://dencode.com/en/string/unicode-escape to convert between escaped `\u` characters and the actual characters. The tool is unable to output the actual characters because of invalid characters that break the tool.
