### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Furluge** [cheahjs/palworld-save-tools#110]
**Common issues before reporting**

**Have you modified the save files**
No.

**Have you tried the latest release**
Using v0.16.0

**Describe the bug**
When attemptig to launch this on a windows system I receive the following error when dragging a sav onto convert.cmd

Checking if Python is installed as python3
C:\Users\<username>\AppData\Local\Microsoft\WindowsApps\python3.exe
Found Python at python3
Python version:
Python 3.8.10
Traceback (most recent call last):
  File "convert.py", line 7, in <module>
    from lib.gvas import GvasFile
  File "C:\Misc\palworld-save-tools-windows-v0.16.0\lib\gvas.py", line 4, in <module>
    from lib.archive import FArchiveReader, FArchiveWriter
  File "C:\Misc\palworld-save-tools-windows-v0.16.0\lib\archive.py", line 72, in <module>
    def instance_id_reader(reader: "FArchiveReader") -> dict[str, UUID]:
TypeError: 'type' object is not subscriptable

**Copy of .sav or .sav.json files**
The file is from a dedicated server, so I'd rather not since I'm not sure which file is which players.

**Comment by cheahjs** [comment]
You need to install at least Python 3.9, you have 3.8 installed
