### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by AdvancedGP** [cheahjs/palworld-save-tools#115]
**Common issues before reporting**

**Have you modified the save files**
No

**Have you tried the latest release**
Yes

**Describe the bug**
im trying to open a character .sav from my friends dedicated server into my own dedicated server, looking for the instanceid, i opened this file, but i get an error, but if i try to open the character .sav file from my own dedicated server it works, but not my friends?

![ffdfs](https://github.com/cheahjs/palworld-save-tools/assets/29183660/4b48b923-574e-4d88-b3ed-112f2422aec9)

**Copy of .sav or .sav.json files**
[A8BF57D1000000000000000000000000.zip](https://github.com/cheahjs/palworld-save-tools/files/14136536/A8BF57D1000000000000000000000000.zip)

**Comment by cheahjs** [comment]
The save file is empty, and thus corrupted.
