### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by Jacobix1** [cheahjs/palworld-save-tools#125]
what i do
![obraz_2024-02-04_142001714](https://github.com/cheahjs/palworld-save-tools/assets/158825636/3ab89498-a63f-44c2-809b-ec487ddd1150)

**Comment by cheahjs** [comment]
Please download the `palworld-save-tools-windows.zip` file from the [releases](https://github.com/cheahjs/palworld-save-tools/releases/latest) page and not just the repo source code.
