### ISSUE TITLE
Get this error 

### ISSUE THREAD

**Issue by SplexArts** [cheahjs/palworld-save-tools#126]
Get this error when i try to convert 

![302069582-8b9ba3fc-37c9-41b7-8c7d-b2822a75182a](https://github.com/cheahjs/palworld-save-tools/assets/29104229/9bc3cc35-6c20-4116-b6a6-cf1dcf6d1a89)

**Comment by cheahjs** [comment]
This is a corrupted save file. As you are using xNul's script instead of this project, you did not get an error message telling you that the save file is corrupt.
