### ISSUE TITLE
Another json to .sav error on level.sav

### ISSUE THREAD

**Issue by InflamedSebi** [cheahjs/palworld-save-tools#13]
![image](https://github.com/cheahjs/palworld-save-tools/assets/1872197/efab3459-51ad-476f-a1a4-27efce8cbe91)

Only happens on level.sav not on player files.

**Comment by cheahjs** [comment]
Does this happen when you convert the `Level.sav` file to JSON and back without making changes to the JSON?

**Comment by wahyucandra30** [comment]
I'm getting this error too. It doesn't happen when converting back to .sav without changing the JSON.

**Comment by wahyucandra30** [comment]
![image](https://github.com/cheahjs/palworld-save-tools/assets/75417145/3512d67a-7f45-45be-9ce0-3f9daada5092)

**Comment by wahyucandra30** [comment]
I think this is user error. I must've missed a bracket somewhere.

**Comment by wahyucandra30** [comment]
Confirmed it was a missing bracket lmao
