### ISSUE TITLE
Handle GVAS parsing entirely in Python

### ISSUE THREAD

**Issue by cheahjs** [cheahjs/palworld-save-tools#15]
Instead of delegating to `uesave-rs`, parse the save game entirely within Python so we can:

1. Remove an external dependency on `uesave-rs`.
2. Avoid shuffling around massive JSON strings and incurring encode/decode costs multiple times

Implementation: `UGameplayStatics::SaveGameToMemory`

**Comment by bho7982** [comment]
I already installed Python 3.12.1 but it says Python is not installed.

**Comment by bho7982** [comment]
![Uploading 1.PNG…]()
