### ISSUE TITLE
Exception: Not a Compressed Palworld Save

### ISSUE THREAD

**Issue by olmijo** [cheahjs/palworld-save-tools#160]
When running the python executable file convert.py in PowerShell on Windows 11 OS, I receive the following error when trying to run the script on my Palworld .sav file:

PS C:\Users\Michael\Documents\Palworld Save To JSON App> python convert.py .\UserOption.sav
Converting .\UserOption.sav to JSON, saving to .\UserOption.sav.json
Decompressing sav file
Traceback (most recent call last):
  File "C:\Users\Michael\Documents\Palworld Save To JSON App\convert.py", line 160, in <module>
    main()
  File "C:\Users\Michael\Documents\Palworld Save To JSON App\convert.py", line 71, in main
    convert_sav_to_json(
  File "C:\Users\Michael\Documents\Palworld Save To JSON App\convert.py", line 105, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\Documents\Palworld Save To JSON App\palworld_save_tools\palsav.py", line 21, in decompress_sav_to_gvas
    raise Exception(
Exception: not a compressed Palworld save, found b'\n\x02\x00' instead of b'PlZ'

**NOTE: I have copied my .sav file from the C:\Users\Michael\AppData\Local\Pal\Saved\SaveGames path and placed it into my Palworld Save To JSON directory. I have also tried the direct path to where the original .sav file is located with the same error message.

**Comment by gamedazed** [comment]
You were pointing to the wrong file, UserOption.sav, what you're looking for is a subdirectory of your SteamID, a further subdirectory of the uuid for that save,  and then a file called Level.sav, if that doesn't make sense just try running `ls C:\Users\Michael\AppData\Local\Pal\Saved\SaveGames\*\*\Level.sav` and it'll show you the full path

**Comment by olmijo** [comment]
Perfect, thanks for the quick response. I got the program working now
thanks!
