### ISSUE TITLE
Syntaxt error in reader.py ?

### ISSUE THREAD

**Issue by jilus22** [cheahjs/palworld-save-tools#19]
Hi, I tryed to use the "convert-single-sav-to-json.bat" by drag and drop a sav file.
The program doesn't work and report a syntax error in the line 139 of reader.py.
I try to find it by myself, downloading again the 0.5 version, differents sav files but I have the same error again and again.
I don't know if I did something wrong or if I don't have the appropriate version for python (3.12)

![image](https://github.com/cheahjs/palworld-save-tools/assets/157718368/69f58855-b7a8-4c18-bef4-adf330574f06)

Thank to your work and your help

**Comment by cheahjs** [comment]
You will need to install Python 3.10 and above for now. I'll update the scripts later to avoid using features from newer Python versions.
