### ISSUE TITLE
Level.sav: UnicodeEncodeError

### ISSUE THREAD

**Issue by PurpleHato** [cheahjs/palworld-save-tools#2]
Hey there, thanks for your work
While trying to convert a level.sav, I stumble across that error
![image](https://github.com/cheahjs/palworld-save-tools/assets/47987542/2f3e3bdb-36e2-49c3-b6bc-1f09a8b42f31)

Which means the conversion is stopped around a value, perhaps having some strange character in there:
![image](https://github.com/cheahjs/palworld-save-tools/assets/47987542/0389fa0e-06cc-44cb-8078-6679c985daa7)

**Comment by cheahjs** [comment]
Should be fixed with https://github.com/cheahjs/palworld-save-tools/commit/a388be9706c1177e5daa61652a54288196ec65a9 and the release of https://github.com/cheahjs/palworld-save-tools/releases/tag/v0.2
