### ISSUE TITLE
Python is installed but still says it is not.

### ISSUE THREAD

**Issue by Jaxson-012** [cheahjs/palworld-save-tools#20]
Hello,

I have python 3.10 installed and it still says python is not installed. I tried with lated version of python as well but still same bug. 

![image](https://github.com/cheahjs/palworld-save-tools/assets/156699965/0fe39d9a-d0ab-482f-b359-3a8f09f47598)

**Comment by taitai2107** [comment]
Open the bat file with notepad++, edit the code to
@ECHO OFF

@REM Check if python is installed, error if not
python --version 2>NUL
IF %ERRORLEVEL% NEQ 0 (
    py --version 2>NUL
    IF %ERRORLEVEL% NEQ 0 (
        python --version 2>NUL
        IF %ERRORLEVEL% NEQ 0 (
            ECHO Python is not installed. Please install python and try again.
            PAUSE
            EXIT /B 1
        ) ELSE (
            SET PYTHON_BIN=python
        )
    ) ELSE (
        SET PYTHON_BIN=py
    )
) ELSE (
    SET PYTHON_BIN=python
)

@REM Switch to script directory
CD /D "%~dp0"

@REM Check if convert-single-sav-to-json.py exists
IF NOT EXIST "convert-single-sav-to-json.py" (
    ECHO convert-single-sav-to-json.py is missing.
    PAUSE
    EXIT /B 1
)

@REM Check if first argument exists
IF "%~1"=="" (
    ECHO You must specify a .sav file to convert.
    PAUSE
    EXIT /B 1
)

@REM Check if uesave.exe exists
IF NOT EXIST "uesave/uesave.exe" (
    ECHO uesave.exe is missing. Please download it from https://github.com/trumank/uesave-rs/releases/download/v0.3.0/uesave-x86_64-pc-windows-msvc.zip and extract uesave.exe into a folder called uesave.
    MKDIR uesave
    PAUSE
    EXIT /B 1
)

ECHO This will convert the save file "%~1" to JSON format.
@REM Ask user if they want to continue
CHOICE /C YN /M "Continue?"
IF %ERRORLEVEL% NEQ 1 (
    EXIT /B 1
)

%PYTHON_BIN% convert-single-sav-to-json.py "uesave/uesave.exe" "%~1"
PAUSE
