### ISSUE TITLE
After dragging Level.sav into convert single sav to json.bat, a prompt of Y/N appears. After pressing Y, any key is pressed to exit, and the json file does not appear in the directory

### ISSUE THREAD

**Issue by CWhedgehog** [cheahjs/palworld-save-tools#26]
After dragging Level.sav into convert single sav to json.bat, a prompt of Y/N appears. After pressing Y, any key is pressed to exit, and the json file does not appear in the directory

**Comment by poudigne** [comment]
@CWhedgehog the file will appear in the directory of the .sav file, not where the .bat file that executed the conversion.

**Comment by MkNan142** [comment]
Same problem
![palworld save](https://github.com/cheahjs/palworld-save-tools/assets/102903889/bc6d7f48-ef54-4332-b4e1-d0006e73585c)

**Comment by KinoshitaRina** [comment]
same

**Comment by Iracy** [comment]
Yeah, same issue here.

![E7Ago6b](https://github.com/cheahjs/palworld-save-tools/assets/7207729/b17760a9-2188-4478-b8a9-21f75287c0ef)

**Comment by cheahjs** [comment]
@Iracy you need to install [Python](https://apps.microsoft.com/detail/9NCVDN91XZQP).

@MkNan142 just checking, do you have Python 3 installed? Your screenshot is missing the python version print that I would expect (but also missing the python shim asking you to download from the Windows Store)

**Comment by szy114514** [comment]
Same problem and solved by running the python script in powershell without cmd.
like:
python convert-single-sav-to-json.py "uesave/uesave.exe" "Level.sav"

**Comment by Nipaoni** [comment]
Same Issue.

Intalled Python 3.12.1 at https://www.python.org/downloads

I followed what was written in https://github.com/EternalWraith/PalEdit?tab=readme-ov-file.
Level.sav doesn't convert to json. 

Don't know related, I'm not an English user.

**Comment by Nipaoni** [comment]
> Same Issue.
> 
> Intalled Python 3.12.1 at https://www.python.org/downloads
> 
> I followed what was written in https://github.com/EternalWraith/PalEdit?tab=readme-ov-file. Level.sav doesn't convert to json.
> 
> Don't know related, I'm not an English user.

Solved

https://github.com/cheahjs/palworld-save-tools/issues/21#issuecomment-1911474897

**Comment by MkNan142** [comment]
> @MkNan142 just checking, do you have Python 3 installed? Your screenshot is missing the python version print that I would expect (but also missing the python shim asking you to download from the Windows Store)

I found my problem,When I manually executed python3, I was prompted to update to version 3.12 from the Windows Store. After installing 3.12, it worked fine.

**Comment by Iracy** [comment]
> @Iracy you need to install [Python](https://apps.microsoft.com/detail/9NCVDN91XZQP).
> 
> @MkNan142 just checking, do you have Python 3 installed? Your screenshot is missing the python version print that I would expect (but also missing the python shim asking you to download from the Windows Store)

Yeah no, I have Python installed. Did [#21](https://github.com/cheahjs/palworld-save-tools/issues/21#issuecomment-1911474897), this fixed it for me. I've got 3.10.9 installed so I simply changed it from python3 to python310

**Comment by Rotnam** [comment]
In Windows , Search for Manage App Execution Aliases and disable python/python3, it will make the regular python working.
