### ISSUE TITLE
char_map error

### ISSUE THREAD

**Issue by Rotnam** [cheahjs/palworld-save-tools#27]
Using the latest version I see here. Im getting this on my Level.sav, corrupted or any suggestion ?

offset 1002377: StructType for ".worldSaveData.MapObjectSpawnerInStageSaveData.SpawnerDataMapByLevelObjectInstanceId.ItemMap.Value" unspecified, assuming Struct(None)
offset 1002657: StructType for ".worldSaveData.ItemContainerSaveData.Value" unspecified, assuming Struct(None)
offset 1353947: StructType for ".worldSaveData.CharacterContainerSaveData.Value" unspecified, assuming Struct(None)
offset 1362163: StructType for ".worldSaveData.GroupSaveDataMap.Key" unspecified, assuming Guid
offset 1362163: StructType for ".worldSaveData.GroupSaveDataMap.Value" unspecified, assuming Struct(None)

Loading JSON
Decoding GroupSaveDataMap
Decoding CharacterSaveParameterMap
Traceback (most recent call last):
  File "C:\users\Wick\Downloads\palworld-save-tools-windows-v0.6\convert-single-sav-to-json.py", line 40, in <module>
    main()
  File "C:\users\Wick\Downloads\palworld-save-tools-windows-v0.6\convert-single-sav-to-json.py", line 32, in main
    decode_character_data(json_blob)
  File "C:\users\Wick\Downloads\palworld-save-tools-windows-v0.6\lib\rawdata.py", line 132, in decode_character_data
    char_map = level_json["root"]["properties"]["worldSaveData"]["Struct"]["value"][
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'CharacterSaveParameterMap'

**Comment by cheahjs** [comment]
Are you willing to share your `Level.sav` file? This isn't expected. The error indicates that your save file is missing the character save data entirely.

**Comment by Rotnam** [comment]
The server power was cut, I assume the Level.sav was corrupted in the
middle of a save or something (my guess). Thanks for looking into this,
might be handy to have some corrupted level detection error.

I tried opening the file in the json url editor someone posted and it seems
like it worked. I wonder if it just stripout the corrupted chars.

Let me know if you want the player save.

Right now, the server just load and is asking for new character creation. I
tried the work around to create a new world, then, put back this world ID,
but no luck.

Thanks!

**Comment by Rotnam** [comment]
Opps I think the email stripped the attachment: 
[C5F4328245BFADC1B3057C95E8664B9E.zip](https://github.com/cheahjs/palworld-save-tools/files/14058853/C5F4328245BFADC1B3057C95E8664B9E.zip)

**Comment by Rotnam** [comment]
Just wanted to add, I left the server running for a bit, the file went from 112k (original at server crash)  to 329k and the convert worked. I will let you know how it goes.

**Comment by cheahjs** [comment]
Just checked the save files you've provided, it's entirely missing character (pals and players) data and any guilds. It looks like a completely fresh save before character creation, hence why the script was failing.

**Comment by chuangmaster** [comment]
I hava the same problem like @Rotnam,
It means I can't recover my saved right?

**Comment by Rotnam** [comment]
> I hava the same problem like @Rotnam, It means I can't recover my saved right?

For me, I assume the file was saving and the server lost power middle-save, leaving half of the actual data missing. Nothing to do, we had to restart the server. I put a PowerShell script now that backup the folder every hour.
