### ISSUE TITLE
Error after convert sav to json on Level.sav

### ISSUE THREAD

**Issue by GreatMach** [cheahjs/palworld-save-tools#3]
![image](https://github.com/cheahjs/palworld-save-tools/assets/44958142/bc7a7e13-abfa-4c14-8419-4241b5d31e4f)

Im trying to use "convert-single-sav-to-json.bat" on my Level.sav but after some minute working, its stop and says what images shows, its happen on 2 of my machines, and on 2 savegames, 1 server with up to 200 diferent players, and on a totally fresh saveworld

sorry for my language, its my first post on Github, thanks for ur time

Whats im doing wrong?

**Comment by mcdiv** [comment]
I'm also having this same issue, I see that you closed the issue - what was your fix?
![Uploading Screenshot 2024-01-24 180337.png…]()

**Comment by cheahjs** [comment]
This should have been fixed with the latest release (https://github.com/cheahjs/palworld-save-tools/releases/tag/v0.2), let me know if it still doesn't work.
