### ISSUE TITLE
Unable to Convert .sav to json

### ISSUE THREAD

**Issue by Newboy37** [cheahjs/palworld-save-tools#33]
I'm trying to get a level.sav converted to json, but when I do i get the following error:

Python 3.7.9
This will convert the save file "C:\Users\Rob\AppData\Local\Pal\Saved\SaveGames\76561197968543780\ECFEC12B4F4040CC8369D58C254B6179\Level.sav" to JSON format.
Continue? [Y,N]?Y
Traceback (most recent call last):
  File "convert-single-sav-to-json.py", line 7, in <module>
    from lib.palsav import *
  File "C:\Users\Rob\OneDrive\Desktop\New folder (2)\lib\palsav.py", line 130, in <module>
    def uesave_to_json_params(uesave_path: str) -> list[str]:
TypeError: 'type' object is not subscriptable
Press any key to continue . . .

I'm not savvy with python or coding at all, and unsure how to resolve this issue.

**Comment by cheahjs** [comment]
Update Python to 3.12, I ended up using features only available in newer versions of Python. Will try and fix this later.

**Comment by kucinkmiaw** [comment]
do i need to delete the older version of python?

**Comment by Newboy37** [comment]
> Update Python to 3.12, I ended up using features only available in newer versions of Python. Will try and fix this later.

That resolved the issue. Now I have a massive JSON i don't know how to navigate lol. Always one thing...
