### ISSUE TITLE
CMD Closes after Putting Save File In

### ISSUE THREAD

**Issue by Cyndergate** [cheahjs/palworld-save-tools#35]
**Common issues before reporting**

**Have you modified the save files**
No

**Have you tried the latest release**
Yes

**Describe the bug**
The cmd does nothing. I've installed python; both locally and via microsoft store to test.
I drag the save file over, and it automatically closes, causing no .json to be created.

I tried on another laptop, and only installed microsoft store python [3.12] - and same issue occurs.
Have tried multiple save files.

**Comment by veltron867** [comment]
Yea I have the same issue also

**Comment by Sivarius** [comment]
Go into cmd file with any text editor, find the last line like %PYTHON_BIN% convert-single-sav-to-json.py "uesave/uesave.exe" "%~1" 

and change "%PYTHON_BIN%" into just "python" 
Should help.

**Comment by Cyndergate** [comment]
Didn't work; issue still persists.

**Comment by cheahjs** [comment]
Please use the [Terminal](https://github.com/cheahjs/palworld-save-tools?tab=readme-ov-file#terminal) instructions if the .cmd file is not working for you.
