### ISSUE TITLE
Sheepball cannot be edited.

### ISSUE THREAD

**Issue by Nipaoni** [cheahjs/palworld-save-tools#38]
PalEdit-main

Python 3.12.1
"E:\SteamLibrary\steamapps\common\Palworld\PalEdit-main\"
Opening file C:/Users/m3062/AppData/Local/Pal/Saved/SaveGames/76561198059212876/7210D0D7470FF4A7DB62238AABAD98FC/Level.sav.json
Error occured: 'CharacterID'
Error occured: 'Sheepball'
Error occured: 'Sheepball'
Created Entity of type PinkCat: <PalInfo.PalObject object at 0x000002606278A120>
Created Entity of type ChickenPal: <PalInfo.PalObject object at 0x000002606278A720>
Created Entity of type ChickenPal: <PalInfo.PalObject object at 0x000002606278A720>
Created Entity of type PinkCat: <PalInfo.PalObject object at 0x000002606278A120>
Error occured: 'Sheepball'
Error occured: 'Sheepball'
Created Entity of type PinkCat: <PalInfo.PalObject object at 0x000002606278A120>
Created Entity of type ChickenPal: <PalInfo.PalObject object at 0x000002606278A720>
Unknown list contains 5 entries

Maybe CharacterID error is because it is not English.

**Comment by cheahjs** [comment]
This looks like an error in PalEdit and not with the underlying save tools.
