### ISSUE TITLE
uesave.exe missing from release?

### ISSUE THREAD

**Issue by jondemars3** [cheahjs/palworld-save-tools#39]
"uesave.exe is missing" when running convert-singe-sav-to-json.cmd. uesave folder is created upon running, but no uesave.exe present

**Comment by cheahjs** [comment]
Download the [palworld-save-tools-windows-v0.7.1.zip](https://github.com/cheahjs/palworld-save-tools/releases/download/v0.7.1/palworld-save-tools-windows-v0.7.1.zip) file and not the zip file, it comes with uesave pre-installed.

**Comment by cheahjs** [comment]
v0.9.0 onwards no longer requires uesave-rs.
