### ISSUE TITLE
CMD closes after typing Y

### ISSUE THREAD

**Issue by lucasvperini** [cheahjs/palworld-save-tools#4]
Hello,

After this screen:
![image](https://github.com/cheahjs/palworld-save-tools/assets/47780889/2907c9ef-9489-4b47-b825-ef444fcf1d2e)

I type Y and the CMD closes, no JSON created.
I need to download something else?
UESave is correctly setup.

There's any way to check logs or so?

**Comment by cheahjs** [comment]
The intended workflow is to grab the zip from the release (https://github.com/cheahjs/palworld-save-tools/releases/latest). The python scripts are likely not located where they are meant to be next to the .bat files if you download the repo as a zip.

**Comment by lucasvperini** [comment]
> The intended workflow is to grab the zip from the release (https://github.com/cheahjs/palworld-save-tools/releases/latest). The python scripts are likely not located where they are meant to be next to the .bat files if you download the repo as a zip.

Ok, it's working now.
There's no way to edit the player inventory in the JSON?
