### ISSUE TITLE
json.decoder.JSONDecodeError keeps happening and have no idea how to fix it.

### ISSUE THREAD

**Issue by Shadowxkitty** [cheahjs/palworld-save-tools#42]
![image_2024-01-26_143354674](https://github.com/cheahjs/palworld-save-tools/assets/157811888/4ad2a414-e657-4d06-bf7a-8a8cd997af4d)

Converting it to json works fine, i put it into save editor change some things, then when i want to change it back to .sav it doesnt work anymore.
edit: I tried without changing anything to the json file and tried to convert it back to the sav file still doesnt work maybe im just missing something idk

**Comment by Shadowxkitty** [comment]
I tried without changing anything to the json file and tried to convert it back to the sav file still doesnt work maybe im just missing something idk

**Comment by cheahjs** [comment]
Are you willing to share your save file? Ideally your JSON file as well (zipping the files should compress them to relatively small sizes).
