### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by antimageee** [cheahjs/palworld-save-tools#43]
File C:\Users\Administrator\Desktop\change\savefiles/Level.sav uncompressed successfully
File C:\Users\Administrator\Desktop\change\savefiles/Level.sav (type: 50) converted to JSON successfully
File C:\Users\Administrator\Desktop\change\savefiles/Players/3E22F785000000000000000000000000.sav uncompressed successfully
File C:\Users\Administrator\Desktop\change\savefiles/Players/3E22F785000000000000000000000000.sav (type: 49) converted to JSON successfully
Converted save files to JSON
JSON files have been parsed
Changes have been made
JSON files have been exported
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\change\fix-host-save.py", line 244, in <module>
    main()
  File "C:\Users\Administrator\Desktop\change\fix-host-save.py", line 121, in main
    json_to_sav(uesave_path, level_json_path)
  File "C:\Users\Administrator\Desktop\change\fix-host-save.py", line 211, in json_to_sav
    with open(sav_file, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\Desktop\\change\\savefiles/Level.sav
Can someone help me fix it?

**Comment by cheahjs** [comment]
Not this project, please raise issues with https://github.com/xNul/palworld-host-save-fix
