### ISSUE TITLE
Try convert sav to json but got error

### ISSUE THREAD

**Issue by natkulkan** [cheahjs/palworld-save-tools#44]
![image](https://github.com/cheahjs/palworld-save-tools/assets/116288713/edf18ecc-2ccb-42fa-ac12-951846965b48)

I was running dedicate server on my PC and then power surge when come back it ask to create new character , I didn't do back up file but keep to corrupt file back up

**Comment by cheahjs** [comment]
Please upload your save file if possible, but it looks like it is corrupt and if that's the case, there isn't much we can do.

**Comment by natkulkan** [comment]
[64D86034000000000000000000000000.zip](https://github.com/cheahjs/palworld-save-tools/files/14075537/64D86034000000000000000000000000.zip)

**Comment by cheahjs** [comment]
![image](https://github.com/cheahjs/palworld-save-tools/assets/818368/03d9e47b-0b0b-4360-8f43-0a93a0ad7c69)
Unfortunately this is corrupted, the entire file has been zeroed out.
