### ISSUE TITLE
Error when using 0.9.0 or 0.10.0

### ISSUE THREAD

**Issue by emannx** [cheahjs/palworld-save-tools#46]
This is a dedicated server Level.sav that I'm trying to recover. The server randomly crashed last night and this is the only file I have
[Level.zip](https://github.com/cheahjs/palworld-save-tools/files/14067766/Level.zip)

**Have you tried the latest release**
Yes, while I was trying to use this tool, it was updated to 0.10.0. I downloaded the new version and the same error came up
![image](https://github.com/cheahjs/palworld-save-tools/assets/58890978/e97f0781-c350-49db-bd33-be16885d8d98)

**Describe the bug**

The script ends with this error, but I've attached a screenshot showing the whole issue. 
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 270: invalid start byte"

Any help would be appreciated! Thanks

**Comment by cheahjs** [comment]
Unfortunately it does look like save file corruption. I can try to take a look in my spare time to see if it's recoverable, but I wouldn't count on it.

**Comment by emannx** [comment]
I think I've figured out what is going as I've re-created the scenario that originally caused my server to crash.

This game is so poorly optimized that building large structures (in my testing with stone), on a large enough scale will cause the server to consume all the ram. I literally watched my RAM usage on the dedicated server increase every few to five walls I was adding would increase my memory usage on the dedicated server by 100mb~ or so.

I would highly advise against building any sort of large structures or mansions until the devs have solved this issue.

Three different worlds had the same problem that eventually caused my server to not even be able to load the world.

I also appreciate you taking the time to respond to my issue and ask that you devote your time and energy into your wonderful tool as I've given up hope that any of those worlds can be recovered without somehow editing the file manually and removing the culprit structures.

**Comment by AScriver** [comment]
@emannx The ["PalWorld-Server-Unoffical-Fix"](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-2) repo may be useful for your case. I have a decently large build and haven't seen my ram exceed 4GB since I started using it.
