### ISSUE TITLE
Drag and drop onto .py file

### ISSUE THREAD

**Issue by DannyHeads** [cheahjs/palworld-save-tools#47]
I am unable to drag and drop the .sav file onto the .py file. When I do nothing runs. The .py file doesn't highlight which leads me to believe that there is no interaction happening.

**Comment by emannx** [comment]
The script has been updated to 1 file, and it is run using the command "python3 convert.py Level.sav" in a CMD window.

**Comment by DannyHeads** [comment]
Ah I was looking under the Windows GUI Instructions section. Thanks!

**Comment by emannx** [comment]
No worries, hope it works !
