### ISSUE TITLE
Issue when running command 

### ISSUE THREAD

**Issue by DannyHeads** [cheahjs/palworld-save-tools#48]
problem when running command to convert .sav. I have python installed from the link that the dev provided on info section. Screen shots below.

![Screenshot 2024-01-26 125501](https://github.com/cheahjs/palworld-save-tools/assets/91427747/79540122-fc92-429b-a5fa-171d45a18fdf)
![Screenshot 2024-01-26 130245](https://github.com/cheahjs/palworld-save-tools/assets/91427747/f2a632db-f670-449f-a4a2-20431a167ae1)

**Comment by cheahjs** [comment]
You needed to `cd` into the directory you had extracted the zip to, ie

```shell
cd Desktop\Pal_World_Sav
python3 convert.py Level.sav
```
