### ISSUE TITLE
Cannot convert Json to Sav

### ISSUE THREAD

**Issue by Reibunn** [cheahjs/palworld-save-tools#5]
![image](https://github.com/cheahjs/palworld-save-tools/assets/157642156/b529acef-f81c-443b-bff6-57c9325228a8)
There is a little problem when it comes to convert Json to sav... 
The screen says it all, if anyone know the problem.

**Comment by cheahjs** [comment]
Did you modify an ID in the JSON? The error indicates that there's an ID that has an incorrect length (7 characters in the first set of characters instead of the expected 8).

**Comment by Reibunn** [comment]
After numerous re-checks, it appears i forgot a 0 on my player ID. 
Thank you, i was just stupid ! (I'm really bad when it comes to manipulating files)
i tried and did the replacement of level.sav too and i have this, does that mean i don't have the right things too? 
![image](https://github.com/cheahjs/palworld-save-tools/assets/157642156/7fc59f1c-4100-4ad3-8b9a-fc8ec04fa39f)

**Comment by cheahjs** [comment]
The JSON file might be incomplete.

Before continuing any further, please update to https://github.com/cheahjs/palworld-save-tools/releases/tag/v0.4 as older versions will produce corrupt `Level.sav` files.
