### ISSUE TITLE
Script runs and does nothing

### ISSUE THREAD

**Issue by Jernee** [cheahjs/palworld-save-tools#55]
**Common issues before reporting**

**Have you modified the save files**
I only changes the python to py.

**Have you tried the latest release**
Yes

**Describe the bug**
When I drop the .sav onto the .cmd files it seems to run fine but just ends with "Press any key to continue." and does nothing.

**Comment by cheahjs** [comment]
Please use the [Terminal](https://github.com/cheahjs/palworld-save-tools?tab=readme-ov-file#terminal) instructions if the .cmd file is not working for you.

**Comment by Jernee** [comment]
> Please use the [Terminal](https://github.com/cheahjs/palworld-save-tools?tab=readme-ov-file#terminal) instructions if the .cmd file is not working for you.

This worked for me.
https://github.com/cheahjs/palworld-save-tools/issues/21#issuecomment-1912225168
