### ISSUE TITLE
About fixing broken save caused by exiting guild

### ISSUE THREAD

**Issue by Bluefissure** [cheahjs/palworld-save-tools#58]
Hi, I have written a small script based on your work to fix the brokwn `Level.sav` caused by exiting guild (by adding the missing players to `CharacterSaveParameterMap` from backup `Level.sav`), the script is available at https://gist.github.com/Bluefissure/f277a3409cdaf09cddbad5983fd01f68

I appreciate all your hard work for the convenience GvasFile module and conversion functions, and do you mind I make a PR for this new feature?

**Comment by Bluefissure** [comment]
Okay I think the latest server 0.1.3.0 fixed this problem, just in case it happens again I'll leave the script there.

**Comment by ryantheleach** [comment]
I ran into this issue on 0.1.3.0 of Palworld.

Will try your script in a bit Bluefissue, thanks! I was about to try to make one.
