### ISSUE TITLE
Guild error after convert

### ISSUE THREAD

**Issue by favoritewky** [cheahjs/palworld-save-tools#59]
**Common issues before reporting**

**Have you modified the save files**
If you have, please ensure that the JSON files are valid.
No
**Have you tried the latest release**
Please download the `palworld-save-tools-windows.zip` file from [releases](https://github.com/cheahjs/palworld-save-tools/releases/latest) in case it's been fixed.
Yes
**Describe the bug**
https://github.com/xNul/palworld-host-save-fix/pull/18
Lost the guild.
**Copy of .sav or .sav.json files**
If possible, attach the .sav or .sav.json file. Add to a zip file to compress it down from gigabytes down to megabytes to make it manageable.

**Comment by cheahjs** [comment]
I'm not sure what the request is here? If you've used the scripts from https://github.com/xNul/palworld-host-save-fix/, then it has nothing to do with this project.

**Comment by favoritewky** [comment]
if use your project , I will lost the guild without any modify json. That url is a reference may be help.



---- Replied Message ----
| From | Jun Siang ***@***.***> |
| Date | 01/27/2024 17:52 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [cheahjs/palworld-save-tools] Guild error after convert (Issue #59) |

I'm not sure what the request is here? If you've used the scripts from https://github.com/xNul/palworld-host-save-fix/, then it has nothing to do with this project.

**Comment by cheahjs** [comment]
Are you saying if you use **only** `palworld-save-tools` to convert to JSON and back that guild data is lost, or the guild data is lost when used in conjunction with `palworld-host-save-fix`?

Without save files I can't debug this any further.

**Comment by favoritewky** [comment]
I use only palworld-save-tools to convert to JSON and back that guild data is lost（Which means when you dead you can't find back your own pal and items）. It may be caused by the reasons discussed at https://github.com/xNul/palworld-host-save-fix/.
After convert to JSON and back.  Then convert it to JSON again there will have an error that provide the process is not complate right. 
```
Loading GVAS file
Traceback (most recent call last):
  File "/home/ubuntu/npc/palworld-save-tools/lib/archive.py", line 108, in read_fstring
    return data.decode(encoding)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/lib/python3.11/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 4096-4097: illegal UTF-16 surrogate
```
