### ISSUE TITLE
The converted file is invalid

### ISSUE THREAD

**Issue by Zacama** [cheahjs/palworld-save-tools#6]
Hello, after converting the Level.sav file into a json file using convert-single-sav-to-json.bat, I did not modify any data. Then, using the convert-single-json-to-sav.bat tool, I converted this json file back into a new Level.sav file and replaced the original game save with it. However, when I open the game and select this save file to enter the game, it gets stuck on the loading screen, completely frozen, and I have to use the Task Manager to close the game process.

I also noticed one thing: the original Level.sav file is a different size from the Level.sav file after two conversions. The latter is slightly larger.

[tojson.log](https://github.com/cheahjs/palworld-save-tools/files/14043999/tojson.log)

**Comment by Zacama** [comment]
[tojson.log](https://github.com/cheahjs/palworld-save-tools/files/14043923/tojson.log)

**Comment by cheahjs** [comment]
The different sizes are expected as a result of different compression levels, but I've managed to reproduce, attempting to fix.

**Comment by cheahjs** [comment]
This should be addressed with #8 and https://github.com/cheahjs/palworld-save-tools/releases/tag/v0.4. I've only tested a single coop save so let me know if you run into any issues.

**Comment by Zacama** [comment]
Hello, I used version v0.4.1 of the tool to try converting the original Level.sav file to json and then back to a .sav file. The save file loaded successfully. I also tried making some simple modifications to the data in the json, then converting it back to a .sav file, and the save file still loaded successfully. Thank you very much @cheahjs , I will close this issue.
