### ISSUE TITLE
RGBA values. (Respond quickly)

### ISSUE THREAD

**Issue by Fakeabe** [cheahjs/palworld-save-tools#71]
Is there any reason they’re formatted like that?
They don’t seem to conform to the values I assign to them.
Could someone explain how they work in this scenario?

**Comment by akutruff** [comment]
Telling someone who is making you a free tool to respond quickly is impolite.

**Comment by Fakeabe** [comment]
> Telling someone who is making you a free tool to respond quickly is impolite.

I wasn’t talking about the dev lol, just anyone who knows anything about the rgb values used.

**Comment by Fakeabe** [comment]
I figured it out, the the values in the RGBA section are slider values. Not rgb values.
