### ISSUE TITLE
A possible code bug?

### ISSUE THREAD

**Issue by eigeen** [cheahjs/palworld-save-tools#85]
P1Z or PlZ? I don't understand the file structure, so someone needs to look at it.

https://github.com/cheahjs/palworld-save-tools/blob/main/lib/palsav.py#L10
https://github.com/cheahjs/palworld-save-tools/blob/main/lib/palsav.py#L12

**Comment by dbwodlf3** [comment]
PIZ is a magic num of palworld. Its like . Extension name.(jpg, png, ...) P1Z its just joke. 
Not a bug.
