### ISSUE TITLE
I cannot seem to update from JSON to SAV

### ISSUE THREAD

**Issue by GuardianMAD** [cheahjs/palworld-save-tools#9]
![image](https://github.com/cheahjs/palworld-save-tools/assets/157658837/19fb706b-026c-4795-a2db-841aea29a4b3)
I follow all the updates (even the one 10 minutes ago) but i keep getting this error, not quite sure what to do with it. I am missing something?

**Comment by cheahjs** [comment]
Did you make any changes to the JSON? There's a group that is missing a `group_type` field.

**Comment by GuardianMAD** [comment]
looks like when i  copy the key/value i didnt copy enough (i still dont know how much i need to copy, the og level file have to many stuff) wasnt able to fix it at the end because it keep trying to make the player make a new character

**Comment by GuardianMAD** [comment]
![image](https://github.com/cheahjs/palworld-save-tools/assets/157658837/19b6e885-7c41-41b5-afb3-e19034ed72b8)
now i got this problem so I am not quite sure what to do next

**Comment by cheahjs** [comment]
The error still indicates a malformed JSON file.
