### ISSUE TITLE
errors trying to convert from .sav to .json

### ISSUE THREAD

**Issue by Temil2006** [cheahjs/palworld-save-tools#91]
tried to convert the level.sav and the each player.sav and get the same exact error no matter what.

C:\palworld-save-tools-windows-v0.15.0>python convert.py 75F87D04000000000000000000000000.sav
Traceback (most recent call last):
  File "convert.py", line 7, in <module>
    from lib.gvas import GvasFile
  File "C:\palworld-save-tools-windows-v0.15.0\lib\gvas.py", line 4, in <module>
    from lib.archive import FArchiveReader, FArchiveWriter
  File "C:\palworld-save-tools-windows-v0.15.0\lib\archive.py", line 44, in <module>
    class FArchiveReader:
  File "C:\palworld-save-tools-windows-v0.15.0\lib\archive.py", line 47, in FArchiveReader
    type_hints: dict[str, str]
TypeError: 'type' object is not subscriptable

have 4 player files and 1 level file, providing 1 of the player files since they all have the same error. Not sure if it helps, but this is from "Dedicated server".

[playersave.zip](https://github.com/cheahjs/palworld-save-tools/files/14102643/playersave.zip)

**Comment by Temil2006** [comment]
nvm, for anyone else who has this issue. it's something with how python was installed for me or something I think, because i moved the files over to a second PC and tried it there and the commands worked 100%, so not sure the cause, but the fix is .. try another PC :)

**Comment by cheahjs** [comment]
You need Python 3.9 or newer.
